app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'PlannerController@planner');

Route::resource('recipes', 'RecipesController');

Route::get('weekly-lists/current-list', ['as' => 'weekly-lists.current-list', 'uses' => 'WeeklyListsController@currentList']);
Route::resource('weekly-lists', 'WeeklyListsController');

Route::get('ingredients/items-in-stock/toggle/{$ingredientId}/{$weeklyListId}', ['as' => 'toggle-item-in-stock-for-ingredient-for-list', 'uses' => 'ItemsInStockController@toggleItemInStockStatus']);

app/Models/Ingredient.php
<?php

namespace Grocer\Models;

use Grocer\ItemInStock;
use Illuminate\Database\Eloquent\Model;
use Grocer\Converters\IngredientListConverter;
use Grocer\Converters\ConvertsStringToIngredient;

class Ingredient extends Model
{
    //
    //
    
    public function toArray() {
        $array = parent::toArray();
        $array['singleLineDescription'] = $this->singleLineDescription;
        return $array;
    }

    protected $fillable = [
        'name',
        'store_section'
    ];

    public static function createForRecipeWithIngredientsString($recipe, $ingredients)
    {

        $converter = new IngredientListConverter(new ConvertsStringToIngredient);
        $items = $converter->convertedList($ingredients);

        foreach ($items as $item)
        {
            if (isset($item['catch-all'])) continue;
            
            $ingredient = static::firstOrCreate(['name' => $item['name']]);

            $recipe->ingredients()->attach($ingredient->id, [
                    'amount' => $item['amount'],
                    'measurement' => $item['measurement']
                ]);
        }
    }

    public function inStock()
    {
        return $this->hasMany(ItemInStock::class);
    }

    public function recipes()
    {
        return $this->belongsToMany(Recipe::class);
    }

    public function getSingleLineDescriptionAttribute()
    {
        $string = [];
        $string[] = $this->pivot->amount;
        $string[] = $this->pivot->measurement;
        $string[] = $this->name;

        return implode(' ', $string);
    }

    public function __toString()
    {
        
        $string[] = $this->pivot->amount;
        $string[] = $this->pivot->measurement;
        $string[] = $this->name;

        return implode(' ', $string);

    }

    public function isInStockForWeeklyListId($weeklyListId)
    {
        return $this->inStock()->forWeeklyListId($weeklyListId)->count();
    }
}

app/Models/Recipe.php
<?php

namespace Grocer\Models;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{

    protected $fillable = [
        'name',
        'url',
        'photo_url'
    ];


    public static function create(array $attributes = [])
    {
        $recipe = parent::create($attributes);
        Ingredient::createForRecipeWithIngredientsString($recipe, $attributes['ingredients']);

        return $recipe;
    }

    public function ingredients()
    {
        return $this->belongsToMany(Ingredient::class)->withPivot(['amount', 'measurement']);
    }

    public function steps()
    {
        return $this->hasMany(RecipeStep::class);
    }

    public function history()
    {
        return $this->belongsToMany(WeeklyList::class)->withPivot(['meal_time', 'meal_date']);
    }
}

app/Http/Controllers/RecipesController.php
<?php

namespace Grocer\Http\Controllers;

use Grocer\Http\Requests\CreateRecipe;
use Grocer\Models\Recipe;
use Illuminate\Http\Request;

use Grocer\Http\Requests;
use Grocer\Http\Controllers\Controller;

class RecipesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        $recipes = Recipe::with(['steps', 'ingredients'])->get();

        return view('recipes.index', compact('recipes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view ('recipes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateRecipe  $request
     * @return Response
     */
    public function store(CreateRecipe $request)
    {
        //
        $recipe = Recipe::create($request->all());

        if ($request->ajax())
        {
            return response()->json(['success' => true, 'recipe' => $recipe]);
        }

        return redirect()->route('recipes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
        $recipe = Recipe::findOrFail($id);
        return view('recipes.show', compact('recipe'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
        $recipe = Recipe::findOrFail($id);
        return view('recipes.edit', compact('recipe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/recipes/create.blade.php
@extends('layouts.standard')

@section('body')

    <h4>Create a recipe</h4>

    @if($errors->any())
        @foreach($errors->all() as $error)
            <p class="text-danger">{{$error}}</p>
            @endforeach
    @endif

    <form action="{{route('recipes.store')}}" method="post">
        {!! csrf_field() !!}

        <div class="row">
            <div class="col-sm-3">
               <input type="text" name="name" placeholder="Recipe Name" class="form-control" value="{{ old("name") }}"/>
            </div>
            <div class="col-sm-4">
                <input type="text" name="url" placeholder="Reference URL" class="form-control" value="{{ old("url") }}"/>
            </div>
            <div class="col-sm-5">
                <input type="text" name="photo_url" placeholder="Photo URL" class="form-control " value="{{ old("photo_url") }}"/>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-sm-6">
                <textarea name="ingredients" rows="5" placeholder="Ingredients" class="form-control ">{{ old('ingredients') }}</textarea>
            </div>
            <div class="col-sm-6">
                <textarea name="instructions" rows="8" placeholder="Step-by-step..." class="form-control">{{ old('instructions') }}</textarea>
            </div>
        </div>
        <br/>

        <button class="btn btn-success">Save Recipe</button>

    </form>

@stop

resources/views/recipes/edit.blade.php
@extends('layouts.standard')

@section('body')
    

@stop

resources/views/recipes/index.blade.php
@extends('layouts.standard')

@section('body')

    <h3>Recipes
        <a href="{{route('recipes.create')}}" class="btn btn-default  pull-right">+ Add new Recipe</a>
    </h3>

    <div class="list-group">
    @foreach($recipes as $recipe)
        <a class="list-group-item" href="{{route('recipes.show', $recipe->id)}}">
           <div class="row">
               <div class="col-sm-1 text-center">
                   <span class="glyphicon glyphicon-bell"></span>
               </div>
               <div class="col-sm-6">
                   {{$recipe->name}}

               </div>
           </div>
        </a>
    @endforeach
    </div>

    @stop

resources/views/recipes/show.blade.php
@extends('layouts.standard')

@section('body')

    <h4>{{$recipe->name}} - {{$recipe->display_prep_time}}</h4>
    <div class="row">
        <div class="col-sm-3">
            {!!$recipe->image!!}
        </div>
        <div class="col-sm-3">
            <div class="list-group">
                @foreach($recipe->ingredients as $ingredient)
                    <div class="list-group-item">
                        {{ $ingredient->single_line_description }}
                    </div>
                @endforeach
            </div>
        </div>
        <div class="col-sm-6">
            {!! $recipe->display_instructions !!}
        </div>
    </div>

@stop